exclude:
  - node_modules
  - script

sass:
  style: :compressed
  
theme: jekyll-theme-midnight

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"

name: yo
title: null
